### ISSUE TITLE
Update to java 11

### ISSUE THREAD

**Issue by tommasobenatti** [astei/SuperbVote#110] opened 2020-12-03 08:36 UTC
Please update the plugin to java 11

**Comment by NotAShelf** [comment] 2020-12-04 07:13
with paper upgrading to java 11 starting from 1.17, I too think that this is necessary!

please update it as soon as possible, as it's the most extensive voting plugin to ever exist :)

**Comment by astei** [comment] 2020-12-04 18:24
Duplicate of #100. Stop telling me that Paper is moving to Java 11, I was there when the decision was made.

**Comment by astei** [comment] 2020-12-04 18:25
I will fix it when I have time. I no longer actively use SuperbVote so the time I spend on it is pretty limited.

**Closed by astei** 2020-12-04 18:24 UTC

**Comment by tommasobenatti** [comment] 2020-12-19 01:53
K, thanks for the update
