### ISSUE TITLE
64 Diamonds

### ISSUE THREAD

**Issue by MrsCaptainElsa** [astei/SuperbVote#78] opened 2019-10-13 13:40 UTC
Hello, so I have a problem with the vip rewards. It gives me 64 diamonds but I want to change it to like 1-10. Where do I change this?

**Comment by astei** [comment] 2020-02-08 07:54
You'll need to modify the `config.yml`. See the wiki for more information.

Closing as this is not a bug.

**Closed by astei** 2020-02-08 07:54 UTC
