### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by TheNety** [astei/SuperbVote#113] opened 2020-12-18 18:45 UTC
Hey, after updating to SuperbVote 0.5.5 I'm getting this error everytime someone joins the server. Can't downgrade to 0.5.4 because there's some error with date formating. :/ Using Paper 1.16.4

```
[19:38:57 WARN]: [SuperbVote] Plugin SuperbVote v0.5.5 generated an exception while executing task 1760660
java.lang.IllegalArgumentException: streaks not enabled
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.4.jar:git-Paper-323]
at io.minimum.minecraft.superbvote.storage.MysqlVoteStorage.getVoteStreak(MysqlVoteStorage.java:369) ~[?:?]
at io.minimum.minecraft.superbvote.storage.VoteStorage.getVoteStreakIfSupported(VoteStorage.java:25) ~[?:?]
at io.minimum.minecraft.superbvote.votes.SuperbVoteListener.lambda$onPlayerJoin$4(SuperbVoteListener.java:139) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-323]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-323]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-323]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by TheNety** [comment] 2020-12-19 15:46
Oh ye and this one on startup
```
[Server thread/ERROR]: [SuperbVote] Unable to initialize database
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CURRENT_DATE(), services TEXT NOT NULL DEFAULT '{}', CHECK(JSON_VALID(services))' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2585) ~[patched_1.16.4.jar:git-Paper-323]
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1464) ~[patched_1.16.4.jar:git-Paper-323]
	at io.minimum.minecraft.superbvote.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120) ~[?:?]
	at io.minimum.minecraft.superbvote.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[?:?]
	at io.minimum.minecraft.superbvote.storage.MysqlVoteStorage.initialize(MysqlVoteStorage.java:83) ~[?:?]
	at io.minimum.minecraft.superbvote.configuration.SuperbVoteConfiguration.initializeVoteStorage(SuperbVoteConfiguration.java:224) ~[?:?]
	at io.minimum.minecraft.superbvote.SuperbVote.onEnable(SuperbVote.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-323]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-323]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-323]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-323]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-323]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-323]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-323]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-323]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-323]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by astei** [comment] 2020-12-20 01:08
Duplicate of #112

**Closed by astei** 2020-12-20 01:08 UTC
